### ISSUE TITLE
where is the defined about MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY and MAIN_WINDOW_WEBPACK_ENTRY

### ISSUE THREAD

**Issue by findmoon** [theolazian/electron-webpack-bootstrap-fontawesome-jquery#1]
hello Théo, I 'm use the cofigure of the current repo. But, I can not find the defined about MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY and MAIN_WINDOW_WEBPACK_ENTRY.

I think these are const variables, And I want add another const variable under the line of defined  MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY . But I dot known where should I add.

Thank you for any advice !

**Comment by findmoon** [comment]
I had knows how use MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY, only by add entryPoints[0].preload.js configure in forge.config.js . 

But, I still dot not know how add another Window and use ANOTHER_WINDOW_PRELOAD_WEBPACK_ENTRY variables correspondingly.

**Comment by theolazian** [comment]
Hello @findmoon, and thanks for your questions!
I am not sure I understood your problem, but I'll try to help 👍 

The two globals ```MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY``` and ```MAIN_WINDOW_WEBPACK_ENTRY``` are part of the Webpack plugin provided by electronforge. You can find more info about it [here](https://www.electronforge.io/config/plugins/webpack). There two globals actually refer to two entry points.

However, if you want to add other views to your project, you should better refer to the documentation of [electron.js](https://www.electronjs.org/docs/latest/api/app) regarding [browser-view](https://www.electronjs.org/docs/latest/api/browser-view) and [browser-window](https://www.electronjs.org/docs/latest/api/browser-window).

I really hope these clarification and documentation will help you through your electron development! 🚀

**Comment by findmoon** [comment]
Hello @theolazian ,and thanks for your answer!
My English is not enough good for descript my questions accurately AND understand [the document](https://www.electronforge.io/config/plugins/webpack). But, I had known that  two globals by reading some times and testing actually.

I had another questions. I need consider how output another preloadjs  to destination dir if I use [browser-view](https://www.electronjs.org/docs/latest/api/browser-view) and [browser-window](https://www.electronjs.org/docs/latest/api/browser-window).

That is to say how specify a js file output and keep unchanged, so that It can be used as preloadjs of another browser-view/window? Because many file will pack into index.js by default! This problem can be solved by sharing preloadjs, and some other ways. I don’t know if there is a more elegant way!

---------------------

I have other situation that more needs to be solved, How use `mainWindow.loadFile()` in electronforge. Now, All the example seem to be `mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)`. My resouses are local, and I think It is not need to make a web Env only for use `loadURL`! But I can not find the method to use `loadFile`.

Thanks again for your answer and advice！

**Comment by theolazian** [comment]
As for the ```loadFile``` method, you can refer to the documentation [here](https://www.electronjs.org/docs/latest/api/web-contents#contentsloadfilefilepath-options). It is quite similar to ```loadURL```. Note that when using ```loadURL```, you can actually pass a file, which is what does this line in ```main.js``` :
``` JS 
// main.js
mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
```
```MAIN_WINDOW_WEBPACK_ENTRY``` refers to the ```ìndex.html``` file.

Now, I am not sure I understand correctly your first question, but if you need to manage different outputs, maybe you can check the [Webpack docs](https://webpack.js.org/guides/output-management/) about it?
If it is rather about adding custom ```js``` file, you can do it freely by creating any file in the ```/src/js/``` folder. Every ```js``` file will be taken into account by Webpack in the output.

I really hope that will help you 👍

**Comment by theolazian** [comment]
And concerning especially preload scripts, you can also refer to the [eletron docs](https://www.electronjs.org/docs/latest/tutorial/process-model#preload-scripts).
It is also addressed in the [Quick start guide](https://www.electronjs.org/docs/latest/tutorial/quick-start).

**Comment by theolazian** [comment]
Lastly, here it is another guess of what you might look for. See this [issue](https://github.com/electron-userland/electron-forge/issues/686#issuecomment-669906036) about referencing the preload for you ```main_window```.

**Comment by findmoon** [comment]
> Lastly, here it is another guess of what you might look for. See this [issue](https://github.com/electron-userland/electron-forge/issues/686#issuecomment-669906036) about referencing the preload for you `main_window`.

Thanks, I had known this it how work. And Thanks again for your patient answer!

**Comment by findmoon** [comment]
> As for the `loadFile` method, you can refer to the documentation [here](https://www.electronjs.org/docs/latest/api/web-contents#contentsloadfilefilepath-options). It is quite similar to `loadURL`. Note that when using `loadURL`, you can actually pass a file, which is what does this line in `main.js` :
> 
> ```js
> // main.js
> mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
> ```
> 
> `MAIN_WINDOW_WEBPACK_ENTRY` refers to the `ìndex.html` file.
> 
> Now, I am not sure I understand correctly your first question, but if you need to manage different outputs, maybe you can check the [Webpack docs](https://webpack.js.org/guides/output-management/) about it? If it is rather about adding custom `js` file, you can do it freely by creating any file in the `/src/js/` folder. Every `js` file will be taken into account by Webpack in the output.
> 
> I really hope that will help you 👍

I had some busy recently,and I will verify what is the result for `mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);` when packaged and released. 

And, I will configure multiple entry and output by check [Webpack docs](https://webpack.js.org/guides/output-management/).

Thanks for your patient and give so greatly answers for me!

**Comment by theolazian** [comment]
You're welcome @findmoon! Now that this issue seems to be answered, I will close it. I was happy to help!

**Comment by findmoon** [comment]
> You're welcome @findmoon! Now that this issue seems to be answered, I will close it. I was happy to help!

Yes, thank you agagin!

**Comment by findmoon** [comment]
@theolazian  I'm sorry borther you!

I had another questions. How make setIcon work! The follow figure is the reason that I setIcon dot work and load img faild!(I guess!).

![image](https://user-images.githubusercontent.com/18387852/143010302-5afc7eda-5277-47d7-9a2d-45f2580145fa.png)

I implement the copy of static assets by using copy-webpack-plugin! 

![image](https://user-images.githubusercontent.com/18387852/143019663-7973f154-efdf-479d-96d6-ecd8b64f7a77.png)

AND,[[SOLVED] Assets missing after packaging using file-loader #1196](https://github.com/electron-userland/electron-forge/issues/1196) seem to be the correct answer. 

BUT, I still do not make it work! I do not know the `options` config if it is the key in the above link, because I add it to file-loader do not work as seem! 

```js
rules.push(
  {
    test: /\.(png|jpe?g|gif|ico|svg)$/, // We will handle of these file extensions
    use: [
      {
        loader: "file-loader",
        options: {
          name: "[path][name].[ext]",
          publicPath: "..", // move up from 'main_window'
          context: "src", // set relative working folder to src
        },
      }
    ]
  },
);
```

How make copied icon file(or static assets) before setIcon?  Can I refer to some correct examples, If I guess wrong.

Express my gratitude again!
